name: AnimalTransport
version: '${project.version}'
main: org.silvius.animaltransport.AnimalTransport
api-version: 1.19
commands:
  transportei:
    usage: /transportei
    aliases: []
    description: Gibt das Transport-Ei Item

